//! Trace record DTOs and append-only trace handles.

use crate::agent::id::{RunId, StepId};
use serde::{Deserialize, Serialize};
use std::{
    fmt,
    sync::{Arc, Mutex},
};
use thiserror::Error;

/// Stable trace node identifier supplied by the caller.
///
/// This id is intentionally not generated by the library. Hosts can use UUIDs,
/// database keys, or deterministic test strings as long as they remain unique
/// within one trace tree.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct TraceNodeId(String);

impl TraceNodeId {
    /// Creates a trace node id from caller-supplied data.
    #[must_use]
    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }

    /// Returns the stored trace node id.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for TraceNodeId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.0)
    }
}

/// Kind of node recorded in an Agent trace tree.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TraceNodeKind {
    /// Root node for an externally initiated run.
    Run,
    /// Agent loop step node.
    Step,
    /// LLM request/response node.
    Llm,
    /// Tool execution node.
    Tool,
    /// Child Agent run node.
    SubAgent,
}

/// Serializable trace record for reconstructing a run tree.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct TraceRecord {
    id: TraceNodeId,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    parent: Option<TraceNodeId>,
    kind: TraceNodeKind,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    label: Option<String>,
}

impl TraceRecord {
    /// Creates a trace record from explicit node data.
    #[must_use]
    pub fn new(
        id: TraceNodeId,
        parent: Option<TraceNodeId>,
        kind: TraceNodeKind,
        label: Option<String>,
    ) -> Self {
        Self {
            id,
            parent,
            kind,
            label: label.and_then(non_empty),
        }
    }

    /// Returns this record's node id.
    #[must_use]
    pub const fn id(&self) -> &TraceNodeId {
        &self.id
    }

    /// Returns this record's parent node id, if it is not the root.
    #[must_use]
    pub const fn parent(&self) -> Option<&TraceNodeId> {
        self.parent.as_ref()
    }

    /// Returns this record's node kind.
    #[must_use]
    pub const fn kind(&self) -> TraceNodeKind {
        self.kind
    }

    /// Returns the optional caller-supplied label.
    #[must_use]
    pub fn label(&self) -> Option<&str> {
        self.label.as_deref()
    }
}

fn non_empty(value: String) -> Option<String> {
    if value.is_empty() { None } else { Some(value) }
}

/// Live handle for appending trace records under a current parent node.
#[derive(Clone, Debug)]
pub struct TraceHandle {
    records: Arc<Mutex<Vec<TraceRecord>>>,
    parent: TraceNodeId,
}

impl TraceHandle {
    /// Creates a trace tree with a root run record.
    #[must_use]
    pub fn new_root(root_id: TraceNodeId, run_id: RunId) -> Self {
        let root = TraceRecord::new(
            root_id.clone(),
            None,
            TraceNodeKind::Run,
            Some(run_id.to_string()),
        );
        Self {
            records: Arc::new(Mutex::new(vec![root])),
            parent: root_id,
        }
    }

    /// Returns a handle that appends future records under `parent`.
    ///
    /// # Errors
    ///
    /// Returns [`TraceError::UnknownParent`] when `parent` is not present in
    /// the shared trace record list.
    pub fn with_parent(&self, parent: TraceNodeId) -> Result<Self, TraceError> {
        let records = self.records.lock().expect("trace mutex poisoned");
        if !records.iter().any(|record| record.id == parent) {
            return Err(TraceError::UnknownParent { parent });
        }
        drop(records);

        Ok(Self {
            records: Arc::clone(&self.records),
            parent,
        })
    }

    /// Returns the current parent for future records created by this handle.
    #[must_use]
    pub const fn current_parent(&self) -> &TraceNodeId {
        &self.parent
    }

    /// Returns a serializable snapshot of all trace records.
    #[must_use]
    pub fn records(&self) -> Vec<TraceRecord> {
        self.records.lock().expect("trace mutex poisoned").clone()
    }

    /// Records an Agent loop step node under the current parent.
    ///
    /// # Errors
    ///
    /// Returns [`TraceError`] when the node id is duplicate or the current
    /// parent is not present.
    pub fn record_step(&self, id: TraceNodeId, step_id: StepId) -> Result<TraceRecord, TraceError> {
        self.record_node(id, TraceNodeKind::Step, Some(step_id.to_string()))
    }

    /// Records an LLM call node under the current parent.
    ///
    /// # Errors
    ///
    /// Returns [`TraceError`] when the node id is duplicate or the current
    /// parent is not present.
    pub fn record_llm(
        &self,
        id: TraceNodeId,
        label: impl Into<String>,
    ) -> Result<TraceRecord, TraceError> {
        self.record_node(id, TraceNodeKind::Llm, Some(label.into()))
    }

    /// Records a tool execution node under the current parent.
    ///
    /// # Errors
    ///
    /// Returns [`TraceError`] when the node id is duplicate or the current
    /// parent is not present.
    pub fn record_tool(
        &self,
        id: TraceNodeId,
        label: impl Into<String>,
    ) -> Result<TraceRecord, TraceError> {
        self.record_node(id, TraceNodeKind::Tool, Some(label.into()))
    }

    /// Records a child Agent run node under the current parent.
    ///
    /// # Errors
    ///
    /// Returns [`TraceError`] when the node id is duplicate or the current
    /// parent is not present.
    pub fn record_sub_agent(
        &self,
        id: TraceNodeId,
        run_id: RunId,
    ) -> Result<TraceRecord, TraceError> {
        self.record_node(id, TraceNodeKind::SubAgent, Some(run_id.to_string()))
    }

    fn record_node(
        &self,
        id: TraceNodeId,
        kind: TraceNodeKind,
        label: Option<String>,
    ) -> Result<TraceRecord, TraceError> {
        let mut records = self.records.lock().expect("trace mutex poisoned");
        if records.iter().any(|record| record.id == id) {
            return Err(TraceError::DuplicateNodeId { node_id: id });
        }
        if !records.iter().any(|record| record.id == self.parent) {
            return Err(TraceError::UnknownParent {
                parent: self.parent.clone(),
            });
        }

        let record = TraceRecord::new(id, Some(self.parent.clone()), kind, label);
        records.push(record.clone());
        Ok(record)
    }
}

/// Classified trace recording failure.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, Error)]
#[serde(rename_all = "snake_case")]
pub enum TraceError {
    /// A trace node id was reused within the same trace tree.
    #[error("duplicate trace node id `{node_id}`")]
    DuplicateNodeId {
        /// Duplicate node id.
        node_id: TraceNodeId,
    },
    /// A trace handle referenced a parent that does not exist in the tree.
    #[error("unknown trace parent `{parent}`")]
    UnknownParent {
        /// Missing parent node id.
        parent: TraceNodeId,
    },
}
